<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Authors>TOYOTA INDUSTRIES CORPORATION</Authors>
    <Company>TOYOTA INDUSTRIES CORPORATION</Company>
    <Copyright>© TOYOTA INDUSTRIES CORPORATION. All rights reserved.</Copyright>
    <DocumentationFile>TICO.GAUDI.Commons.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="M2MqttDotnetCore" Version="1.0.8" />
    <PackageReference Include="Gaudi.Azure.Devices.Client" Version="6.0.1" />
  </ItemGroup>

</Project>
