name: Build and Test

on:
  pull_request:
    branches: 
      - 'develop'
      - main
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - 'develop'
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # .NETのセットアップ
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # パッケージ復元
    - name: Restore NuGet packages
      run: dotnet restore
      env:
        NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS: 60
        NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS: 60

    - name: Build Commons project
      run: dotnet build ./src/TICO.GAUDI.Commons.csproj -c Release

    - name: Build Test project
      run: dotnet build ./src/TICO.GAUDI.Commons.Test.csproj -c Release

    - name: Test Commons project
      run: dotnet test ./src/TICO.GAUDI.Commons.Test.csproj --no-restore --filter "Phase!=Unit"
      env:
        NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS: 60
        NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS: 60

    - name: Pack Commons project
      env:
        VERSION: ${{ github.event.release.tag_name }}
      run: |
        dotnet pack ./src/TICO.GAUDI.Commons.csproj -c Release -o ./commons -p:PackageVersion=${{ env.VERSION }}

    - name: Pack Test project
      env:
        VERSION: ${{ github.event.release.tag_name }}
      run: |
        dotnet pack ./src/TICO.GAUDI.Commons.Test.csproj -c Release -o ./test -p:PackageVersion=${{ env.VERSION }}