name: Publish NuGet Package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # .NETのセットアップ
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    # GitHub Packages 用の NuGet 認証の設定
    - name: Configure GitHub Packages
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    # パッケージ復元
    - name: Restore NuGet packages
      run: dotnet restore
      env:
        NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS: 60
        NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS: 60

    # ビルド
    - name: Build Commons project
      run: dotnet build ./src/TICO.GAUDI.Commons.csproj -c Release

    - name: Build Test project
      run: dotnet build ./src/TICO.GAUDI.Commons.Test.csproj -c Release

    # テスト
    - name: Test Commons project
      run: dotnet test ./src/TICO.GAUDI.Commons.Test.csproj --no-restore --filter "Phase!=Unit"
      env:
        NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS: 60
        NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS: 60

    # バージョンをリリースタグ名に設定し、プロジェクトのパッケージを作成
    - name: Pack Commons project
      env:
        VERSION: ${{ github.event.release.tag_name }}
      run: |
        dotnet pack ./src/TICO.GAUDI.Commons.csproj -c Release -o ./commons -p:PackageVersion=${{ env.VERSION }}

    - name: Pack Test project
      env:
        VERSION: ${{ github.event.release.tag_name }}
      run: |
        dotnet pack ./src/TICO.GAUDI.Commons.Test.csproj -c Release -o ./test -p:PackageVersion=${{ env.VERSION }}

    # プロジェクトのパッケージをGitHub Packagesにプッシュ
    - name: Publish Commons package
      run: dotnet nuget push "./commons/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/Project-GAUDI/index.json" --skip-duplicate

    - name: Publish Test package
      run: dotnet nuget push "./test/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/Project-GAUDI/index.json" --skip-duplicate