name: Publish NuGet Package

on:
  push:
    tags:
      - 'Release/*' 

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    # .NETのセットアップ
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x' # .NETバージョンに応じて調整

    # パッケージ復元
    - name: Restore dependencies
      run: dotnet restore

    # ビルド
    - name: Build
      run: dotnet build --no-restore -c Release

    # テスト
    - name: Test
      run: dotnet test --no-build -c Release

    - name: Publish package
      run: |
        dotnet pack --no-build -c Release -o nupkg
        dotnet nuget push "nupkg/*.nupkg" --api-key ${{secrets.GITHUB_TOKEN}} --source "https://nuget.pkg.github.com/Project-GAUDI/index.json" --skip-duplicate
